/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciocaracteres2;

/**
 *
 * @author david
 */
public class FrmMorse extends javax.swing.JFrame {
    String a = "*-";
    String b = "-***";
    String c = "-*-*";
    String d = "-**";
    String e = "*";
    String f = "**-*";
    String g = "--*";
    String h = "****";
    String i = "**";
    String j = "*---";
    String k = "-*-";
    String l = "*-**";
    String m = "--";
    String n = "-*";
    String o = "---";
    String p = "*--*";
    String q = "--*-";
    String r = "*-*";
    String s = "***";
    String t = "-";
    String u = "**-";
    String v = "***-";
    String w = "*--";
    String x = "-**-";
    String y = "-*--";
    String z = "--**";
    String sps = "x";
    int tamano;
    int contador;
    char [] frase;
    String [] frasec;
    String impresion;
    /**
     * Creates new form FrmMorse
     */
    public FrmMorse() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMensajenormal = new javax.swing.JTextField();
        btnMorse = new javax.swing.JButton();
        BtnNormal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLetra = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(txtMensajenormal);
        txtMensajenormal.setBounds(40, 60, 330, 40);

        btnMorse.setText("Morse");
        btnMorse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMorseActionPerformed(evt);
            }
        });
        getContentPane().add(btnMorse);
        btnMorse.setBounds(20, 260, 61, 23);

        BtnNormal.setText("Texto");
        BtnNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNormalActionPerformed(evt);
            }
        });
        getContentPane().add(BtnNormal);
        BtnNormal.setBounds(320, 260, 61, 23);

        jLabel1.setText("Traducir a:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 230, 60, 14);

        jLabel2.setText("Traductor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 20, 50, 14);

        btnLetra.setText("Letra");
        btnLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLetraActionPerformed(evt);
            }
        });
        getContentPane().add(btnLetra);
        btnLetra.setBounds(167, 180, 57, 23);

        jLabel3.setText("Click cada vez que ingrese una letra:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 160, 180, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMorseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMorseActionPerformed
       tamano=txtMensajenormal.getText().length();
       System.out.println(String.valueOf(tamano));
              
       StringBuilder textoBuilder= new StringBuilder("");
       for(contador=0;contador<=tamano-1;contador++)
       {
           frase[contador]=txtMensajenormal.getText().charAt(contador);
           System.out.println(txtMensajenormal.getText().charAt(contador));
           
           
       }
       
       for(contador=0;contador<=tamano-1;contador++)
       {
         frasec[contador]=  Character.toString(frase[contador]);
                   
       }   
       for(contador=0;contador<=tamano-1;contador++)
       {
           if("a".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
                              
           }
           if("b".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
               
           }
           if("c".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
               
           }
           if("d".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
               
           }
           if("e".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
               
           }
           if("f".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
               
           }
           if("g".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
               
           }
           if("h".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
               
           }
           if("i".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
           }
           if("j".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
           }
           if("k".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
           }
           if("l".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
           }
           if("m".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
           }
           if("n".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
           }
           if("o".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
           }
           if("p".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
           }
           if("q".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
           }
           if("r".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
           }
           if("s".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
           }
           if("t".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
           }
           if("u".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
           }
           if("v".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
           }
           if("w".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
           }
           if("x".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
           }
           if("y".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
           }
           if("z".equals(frasec[contador]))
           {
               textoBuilder.append(frase[contador]);
           }
           if(" ".equals(frasec[contador]))
           {
               textoBuilder.append("x");
           }
        

       }
       System.out.println(textoBuilder);

       
    }//GEN-LAST:event_btnMorseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void BtnNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNormalActionPerformed
       tamano=txtMensajenormal.getText().length();
       System.out.println(String.valueOf(tamano));            
       StringBuilder textoBuilder1= new StringBuilder("");

       for(contador=0;contador<=tamano-1;contador++)
       {        
        
                if(a.equals(frasec[contador]))
                {
                    textoBuilder1.append("a");
                   
                }
                if(b.equals(frasec[contador]))
                {
                    textoBuilder1.append("b");
                }
                if(c.equals(frasec[contador]))
                {
                    textoBuilder1.append("c");
                }
                if(d.equals(frasec[contador]))
                {
                    textoBuilder1.append("d");
                    
                }
                if(e.equals(frasec[contador]))
                {
                    textoBuilder1.append("e");

                }
                if(f.equals(frasec[contador]))
                {
                    textoBuilder1.append("f");

                }
                if(g.equals(frasec[contador]))
                {
                    textoBuilder1.append(g);

                }
                if(h.equals(frasec[contador]))
                {
                    textoBuilder1.append("h");
                    
                }
                if(i.equals(frasec[contador]))
                {
                    textoBuilder1.append("i");

                }
                if(j.equals(frasec[contador]))
                {
                    textoBuilder1.append("j");

                }
                if(k.equals(frasec[contador]))
                {
                    textoBuilder1.append("k");

                }
                if(l.equals(frasec[contador]))
                {
                    textoBuilder1.append("l");

                }
                if(m.equals(frasec[contador]))
                {
                    textoBuilder1.append("m");

                }
                if(n.equals(frasec[contador]))
                {
                    textoBuilder1.append("n");

                }
                if(o.equals(frasec[contador]))
                {
                    textoBuilder1.append("o");

                }
                if(p.equals(frasec[contador]))
                {
                    textoBuilder1.append("p");

                }
                if(q.equals(frasec[contador]))
                {
                    textoBuilder1.append("q");

                }
                if(r.equals(frasec[contador]))
                {
                    textoBuilder1.append("r");

                }
                if(s.equals(frasec[contador]))
                {
                    textoBuilder1.append("s");

                }
                if(t.equals(frasec[contador]))
                {
                    textoBuilder1.append("t");

                }
                if(u.equals(frasec[contador]))
                {
                    textoBuilder1.append("u");

                }
                if(v.equals(frasec[contador]))
                {
                    textoBuilder1.append("v");

                }
                if(w.equals(frasec[contador]))
                {
                    textoBuilder1.append("w");

                }
                if(x.equals(frasec[contador]))
                {
                    textoBuilder1.append("x");

                }        
                if(y.equals(frasec[contador]))
                {
                    textoBuilder1.append(y);

                }        
                if(z.equals(frasec[contador]))
                {
                    textoBuilder1.append("z");

                }        
                if(sps.equals(frasec[contador]))
                {
                    textoBuilder1.append(" ");

                }
                
        
       }
       System.out.println(textoBuilder1);
    }//GEN-LAST:event_BtnNormalActionPerformed

    private void btnLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLetraActionPerformed
        int con=0;
        frasec[con]=txtMensajenormal.getText();
        con++;
    }//GEN-LAST:event_btnLetraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMorse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMorse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMorse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMorse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMorse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNormal;
    private javax.swing.JButton btnLetra;
    private javax.swing.JButton btnMorse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtMensajenormal;
    // End of variables declaration//GEN-END:variables
}
